function [abm_sample] = abm_sample()
    abm_sample = struct(...
        'cuticleUndulationsAspectRatio', 5.0, ...
        'epidermisCellCapsAspectRatio',  5.0, ...
        'palisadeCellCapsAspectRatio',   1.0, ...
        'spongyCellCapsAspectRatio',     5.0, ...
        'wholeLeafThickness',            2.04e-4, ...
        'dryBulkDensity', 1.19e-5 / (4.1e-4 * 1.66e-4), ...
        'airVolumeFraction', 0.31, ...
        'proteinFraction', 0.0, ...
        'celluloseFraction', 0.0, ...
        'ligninFraction', 0.0, ...
        'antidermalScattererFraction', 0.3872, ...
        'mesophyllScattererFraction', 0.3872, ...
        'chlorophyllAConcentration', 3.978, ...
        'chlorophyllBConcentration', 1.161, ...
        'carotenoidMesophyllConcentration', 1.32 ...
    );
end

