function [abm_sample] = abm_sample()
    abm_sample = struct(...
        'wholeLeafThickness',               1e-4, ...
        'cuticleUndulationsAspectRatio',    1.0, ...
        'epidermisCellCapsAspectRatio',     1.0, ...
        'spongyCellCapsAspectRatio',        1.0, ...
        'palisadeCellCapsAspectRatio',      1.0, ...
        'proteinConcentration',             0.0, ...
        'celluloseConcentration',           0.0, ...
        'linginConcentration',              0.0, ...
        'chlorophyllAConcentration',        0.0, ...
        'chlorophyllBConcentration',        0.0, ...
        'carotenoidConcentration',          0.0, ...
        'mesophyllFraction',                0.8 ...
    );
end

